# Site settings
title: 
header-img: img/home-bg.png
email: sonia.d.nicas@gmail.com
copyright_name: s-nicas
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  s-nicas
learn_profile: s-nicas
email_username: sonia.d.nicas@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
